### ISSUE TITLE
User-specified `field` does not work correctly

### ISSUE THREAD

**Issue by sakshamgupta05** [joaomdmoura/machinery#59] opened 2019-10-04 11:13 UTC
State transitions do not work as expected when I define `field: :status`.

Eg:
```elixir
field: :status,
states: ["a", "b", "c"],
transitions: %{
  "b" =>  "c",
}

iex> Machinery.transition_to(%{status: "b"}, YourStateMachine, "c")
{:error, "Transition to this state isn't declared."}
```

**Comment by aenglisc** [comment] 2019-10-10 14:31
I tried reproducing it in `iex` and it seems to be working fine. Perhaps there's something external affecting the result?

For the record:
Lib version: `0.17.0`,
Elixir: `1.8.2`,
Erlang: `21`
erts: `10.3`

```elixir
iex(11)> defmodule A do
...(11)> defstruct status: "a"
...(11)> end
warning: redefining module A (current version defined in memory)
  iex:11

{:module, A,
 <<70, 79, 82, 49, 0, 0, 5, 212, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 178,
   0, 0, 0, 18, 8, 69, 108, 105, 120, 105, 114, 46, 65, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 7, 99, 111, 109, 112, ...>>, %A{status: "a"}}
iex(12)> defmodule B do                                               
...(12)> use Machinery,
...(12)> field: :status,
...(12)> states: ["a", "b", "c"],
...(12)> transitions: %{"b" => "c"}
...(12)> end
warning: redefining module B (current version defined in memory)
  iex:12

{:module, B,
 <<70, 79, 82, 49, 0, 0, 5, 228, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 213,
   0, 0, 0, 19, 8, 69, 108, 105, 120, 105, 114, 46, 66, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 7, 99, 111, 109, 112, ...>>, {:_field, 0}}
iex(13)> Machinery.transition_to %A{}, B, "c"
{:error, "Transition to this state isn't declared."}
iex(14)> Machinery.transition_to %A{status: "b"}, B, "c"
{:ok, %A{status: "c"}}
iex(15)> Machinery.transition_to %{status: "b"}, B, "c" 
{:ok, %{status: "c"}}
```

**Comment by sakshamgupta05** [comment] 2019-10-12 01:36
I tried executing the same commands on my machine. I am still getting the same results as before. I think the problem is specific to the elixir/erlang version I am using.

My Machine
Lib version: `0.17.0`,
Elixir: `1.9.1`,
Erlang: `22`,
erts: `10.4.4`

```elixir
iex(1)> defmodule A do
...(1)> defstruct status: "a"
...(1)> end
{:module, A,
 <<70, 79, 82, 49, 0, 0, 5, 216, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 178,
   0, 0, 0, 18, 8, 69, 108, 105, 120, 105, 114, 46, 65, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 7, 99, 111, 109, 112, ...>>, %A{status: "a"}}
iex(2)> defmodule B do
...(2)> use Machinery,
...(2)> field: :status,
...(2)> states: ["a", "b", "c"],
...(2)> transitions: %{"b" => "c"}
...(2)> end
{:module, B,
 <<70, 79, 82, 49, 0, 0, 5, 220, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 213,
   0, 0, 0, 19, 8, 69, 108, 105, 120, 105, 114, 46, 66, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 7, 99, 111, 109, 112, ...>>, {:_field, 0}}
iex(3)> Machinery.transition_to %A{}, B, "c"
{:error, "Transition to this state isn't declared."}
iex(4)> Machinery.transition_to %A{status: "b"}, B, "c"
{:error, "Transition to this state isn't declared."}
iex(5)> Machinery.transition_to %{status: "b"}, B, "c"
{:error, "Transition to this state isn't declared."}
```

It works fine if I use the default `state` instead of `status`

```elixir
iex(1)> defmodule A do
...(1)> defstruct state: "a"
...(1)> end
{:module, A,
 <<70, 79, 82, 49, 0, 0, 5, 216, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 178,
   0, 0, 0, 18, 8, 69, 108, 105, 120, 105, 114, 46, 65, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 7, 99, 111, 109, 112, ...>>, %A{state: "a"}}
iex(2)> defmodule B do
...(2)> use Machinery,
...(2)> states: ["a", "b", "c"],
...(2)> transitions: %{"b" => "c"}
...(2)> end
{:module, B,
 <<70, 79, 82, 49, 0, 0, 5, 216, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 212,
   0, 0, 0, 19, 8, 69, 108, 105, 120, 105, 114, 46, 66, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 7, 99, 111, 109, 112, ...>>, {:_field, 0}}
iex(3)> Machinery.transition_to %A{}, B, "c"
{:error, "Transition to this state isn't declared."}
iex(4)> Machinery.transition_to %A{state: "b"}, B, "c"
{:ok, %A{state: "c"}}
iex(5)> Machinery.transition_to %{state: "b"}, B, "c"
{:ok, %{state: "c"}}
```

**Comment by aenglisc** [comment] 2019-10-12 10:03
I've just tried the same on my home laptop running Elixir 1.9.1, Erlang 22 and erts 10.5.2, still working as intended. 🤔

**Comment by sakshamgupta05** [comment] 2019-10-12 22:37
I tried doing the same on another laptop running fedora (earlier I tried on mac), still not working.

Some additional info that might help in replicating/debugging the issue.

Environment
```
Erlang/OTP 21 [erts-10.3.5.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.9.0) - press Ctrl+C to exit (type h() ENTER for help)
```

mix.exs
```elixir
defmodule Mach3.MixProject do
  use Mix.Project

  def project do
    [
      app: :mach3,
      version: "0.1.0",
      elixir: "~> 1.9",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
      {:machinery, "~> 0.17.0"},
      {:poison, "~> 4.0"}
    ]
  end
end
```

**Comment by joaomdmoura** [comment] 2019-10-25 13:59
I think this might be relate to the version you are using maybe?
I'm pretty sure this is not happening in master anymore, just double checked it last night, I'll probably cut a new version over the weekend but if you use master for now instead of 0.17.0 that should work like a charm.
I'll keep this open for now until I cut a new version

**Comment by joaomdmoura** [comment] 2019-11-16 00:19
Folks, happy to announce I just release version 1.0.0.
https://hex.pm/packages/machinery

It's a 1.0.0 because of all the breaking changes it has, like removing the dashboard feature a dependency on phoenix.

Closing this for now, let me know if you find any bugs.

**Closed as completed by joaomdmoura** 2019-11-16 00:19 UTC
Labels: Hacktoberfest
